# Generated by Django 2.1.2 on 2018-10-14 03:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ogbam', '0004_auto_20181010_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtime',
            name='amount',
            field=models.CharField(choices=[('100', '#100'), ('500', '#500'), ('1000', '#1000'), ('5000', '#5000'), ('1000', '#1000')], default='#100', max_length=30),
        ),
        migrations.AlterField(
            model_name='airtime',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 3, 56, 55, 69583, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='data',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 3, 56, 55, 82584, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='share_and_sell',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 3, 56, 55, 63583, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 3, 56, 55, 75583, tzinfo=utc)),
        ),
    ]
