# Generated by Django 2.1.2 on 2018-10-14 12:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ogbam', '0005_auto_20181013_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtime',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 12, 16, 29, 238233, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Balance',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 12, 16, 29, 243234, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='share_and_sell',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 12, 16, 29, 235233, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 12, 16, 29, 241234, tzinfo=utc)),
        ),
    ]
