# Generated by Django 2.1.2 on 2018-10-14 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ogbam', '0006_auto_20181014_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtime',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 12, 24, 2, 295147, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='data',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 12, 24, 2, 298147, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='share_and_sell',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='share_and_sell',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 12, 24, 2, 293147, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 14, 12, 24, 2, 297147, tzinfo=utc)),
        ),
    ]
