# Generated by Django 2.1.2 on 2018-10-15 00:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ogbam', '0009_auto_20181014_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Balance',
        ),
        migrations.AlterField(
            model_name='airtime',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 0, 21, 39, 47166, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='data',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 0, 21, 39, 51166, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='share_and_sell',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 0, 21, 39, 45165, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 0, 21, 39, 49166, tzinfo=utc)),
        ),
    ]
