# Generated by Django 2.1.2 on 2018-10-15 00:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ogbam', '0011_auto_20181014_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Account_Balance',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='airtime',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 0, 28, 14, 262771, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='data',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 0, 28, 14, 265771, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='share_and_sell',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 0, 28, 14, 260770, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 0, 28, 14, 264771, tzinfo=utc)),
        ),
    ]
