# Generated by Django 2.1.2 on 2018-10-18 02:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ogbam', '0012_auto_20181014_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtime',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 2, 45, 17, 710496, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='data',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 2, 45, 17, 712496, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='share_and_sell',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 2, 45, 17, 708496, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 2, 45, 17, 711496, tzinfo=utc)),
        ),
    ]
